#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: im.vec.*.entity
  mapperLocations: classpath*:mapper/**/*.xml

---

#开发配置
spring:
  profiles: dev

  datasource:
#    url: jdbc:mysql://116.62.148.24:3306/vote?characterEncoding=utf-8&useSSL=false&useInformationSchema=true
    url: jdbc:mysql://116.62.141.216:3306/vote?characterEncoding=utf-8&useSSL=false&useInformationSchema=true
    #    url: jdbc:mysql://118.190.217.75:3306/skybluefly?characterEncoding=utf-8&useSSL=false&useInformationSchema=true
    username: root
    password: ZHpark1742!
    #    password: uAiqwVwjJ8-i
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    im.vec: debug